### ISSUE TITLE
Warning: Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by sch19970102** [franga2000/BungeeStatus#11]
Warning: Invalid argument supplied for foreach() in /www/public_html/index.php on line 11
If it does not support Chinese?

**Comment by sch19970102** [comment]
Warning: Invalid argument supplied for foreach() in /www/public_html/admin/index.php on line 22
Warning: Invalid argument supplied for foreach() in /www/public_html/admin/index.php on line 57

**Comment by franga2000** [comment]
If the change doesn't fix it, please reopen the issue

**Comment by sch19970102** [comment]
The problem is still there.

**Comment by franga2000** [comment]
Could you post your `servers.json` file? You can remove the IPs and ports if you'd like
