### ISSUE TITLE
Stuck on loading / checking

### ISSUE THREAD

**Issue by Elixzar** [franga2000/BungeeStatus#12]
http://emporior.net/status

At skyblock, query and others are enabled but its stuck at Checking... (I changed it from Loading to checking), PHP 5.5 and every other server works, anything wrong?

**Comment by franga2000** [comment]
Your `servers.json` file is not formatted corectly. It contains an `object` instead of a `list`.
Here's the correct format:
```json
[
    {},
    {}
]
```
Here's a bit more detailed tutorial on the [wiki](https://github.com/franga2000/BungeeStatus/wiki/Manual-Configuration#serversjson).

**Comment by Elixzar** [comment]
The wiki is outdated, I guess...
My config looks alot different and im using the latest version and never touched the servers.json, you should fix it in my opinion.

http://hastebin.com/vamevupuma.dos Is my config.

**Comment by Elixzar** [comment]
Not 100% understanding what you mean either, so if you can fix my config, I'd appreciate it.
Thanks!

**Comment by franga2000** [comment]
The wiki isn't outdated, your config is broken and I have no idea how such a config could have been generated automatically.
Here's a fixed version: http://hastebin.com/etowokaquj.json

**Comment by Elixzar** [comment]
Ah, thanks! Works fine now but I downloaded BungeeStatus from spigot, uploaded it and added servers from the admin panel so yeah.

PS: Take a look at spigot forums and reply to me if you can, thanks.
