### ISSUE TITLE
Player columns in config.json

### ISSUE THREAD

**Issue by Elixzar** [franga2000/BungeeStatus#13]
When changing playercolumns in config.json to 3 or more, the player columns will glitch a little bit and stay at 2.

Anything wrong?

**Comment by franga2000** [comment]
I know about this issue, but I haven't fixed because I'm working on a different layout for the player list.
It'll be in the next update ([soon](http://www.wowwiki.com/Soon)).

**Comment by Elixzar** [comment]
Awesome! Cant wait.

**Comment by franga2000** [comment]
Invalidated by version [1.7](https://github.com/franga2000/BungeeStatus/releases/tag/1.7).
