### ISSUE TITLE
Invalid Headers / Already Set

### ISSUE THREAD

**Issue by Fabricio20** [franga2000/BungeeStatus#16]
Hello, when I join my /admin page and log in, I get 2 "Invalid Headers" notifications on my screen. 
## 

Warning: Cannot modify header information - headers already sent by (output started at public_html/status/include/header.php:8) in public_html/status/include/password_protect.php on line 50

Warning: session_start() [function.session-start]: Cannot send session cache limiter - headers already sent (output started at public_html/status/include/header.php:8) in public_html/status/admin/index.php on line 11
## 

Also on the Logout page:

Warning: Cannot modify header information - headers already sent by (output started at public_html/status/include/header.php:8) in public_html/status/include/password_protect.php on line 9

Warning: Cannot modify header information - headers already sent by (output started at public_html/status/include/header.php:8) in public_html/status/include/password_protect.php on line 10
## 

And those mean you cant add servers nor save the config.
If I set CHMOD for those directories they simply give me an 500 ( ISE ).

Thanks in advance!

**Comment by franga2000** [comment]
All of these are caused by the same problem: some servers being weird and sending headers before all of the code is finished running. 

Try setting the option `session_fix` to `true` in the `config.json`.

**Comment by Fabricio20** [comment]
I've set Session fix to true and I'm still getting errors, but now only the second one is displaying:

```
Warning: Cannot modify header information - headers already sent by (output started at public_html/status/include/header.php:8) in public_html/status/include/password_protect.php on line 50
```

Also I still can't change any config nor add servers ( It redirects me to the login page ).

**Comment by franga2000** [comment]
Try editing the header file ([/include/header.php](https://github.com/franga2000/BungeeStatus/blob/master/include/header.php)) and add `ob_start();` to the end of  [line 5](https://github.com/franga2000/BungeeStatus/blob/master/include/header.php#L5).

Keep in mind, this is a very hacky way of fixing this. I recommend updating your PHP if possible.

**Comment by Fabricio20** [comment]
Ok, those errors are fixed, but now this:

```
Warning: Invalid argument supplied for foreach() in public_html/status/index.php on line 11
```

Currently running PHP 5.2.17
Edit: Also found this one:

```
Warning: array_merge() [function.array-merge]: Argument #1 is not an array in public_html/status/config.php on line 10
```

**Comment by franga2000** [comment]
There's something wrong with your `config.json`. Can you give me the URL of your site so I can take a look?

**Comment by Fabricio20** [comment]
Http://voltugames.com/status

**Comment by franga2000** [comment]
Your `servers.json` and `config,json` files aren't accessible (or empty).

**Comment by Fabricio20** [comment]
I've CHMOD 777 on both files now, and I just get more errors ._.
They are not empty, if I download them, everything seems ok ;/

**Comment by franga2000** [comment]
Try to access them from your browser: http://voltugames.com/status/config.json
The webserver (and probably PHP) sees it as empty

**Comment by Fabricio20** [comment]
Yeah, I know, I just don't get why its empty, directory access are granted ;/

**Comment by franga2000** [comment]
Put the following code in a `.php` file and open it in your browser: 

``` php
<?php
if (!file_exists("config.json")) {
    file_put_contents("config.json", file_get_contents("https://raw.githubusercontent.com/franga2000/BungeeStatus/master/config.json"));
    echo("config.json downloaded! \n");
}
if (!file_exists("servers.json")) {
    file_put_contents("servers.json", "[]");
    echo("servers.json created! \n");
}
echo("Config: \n");
var_dump(file_get_contents("config.json"));
echo("\nServers: ");
var_dump(file_get_contents("servers.json"));
?>
```

If you see something like `Config: bool(false)  Servers: bool(false)` then delete both of the config files and run the script again. 
It should now say `Downloaded config.json! Created servers.json!`. Then you should see a dump of the files (it's easier to read if you open the source (CTRL+U)).

**Comment by Fabricio20** [comment]
Well, I did what you said and run the script, it first outputted null values so I removed both files and ran it again, the files were downloaded but they still show as empty on web browser.
Edit: 
`Warning: Invalid argument supplied for foreach() in public_html/status/index.php on line 11`
This is happening againg, and the files are not empty anymore ( you can now see content ).

**Comment by franga2000** [comment]
Well the PHP Manual says that the functioun outputs null only if it's somehow disabled (`php.ini` maybe?).

Make another php file containing the following and send me the link:

``` php
<?php phpinfo(); ?>
```

It's probably some kind of weid config option set by your host.

**Comment by Fabricio20** [comment]
http://voltugames.com/status/info.php

**Comment by franga2000** [comment]
This doesn't make any sense. There's nothing wrong with my script and I can't find anything wrong with your server either. Honestly, I have no idea what's going on.

I'd recommend you to contact your hosting provider and ask them to take a look at it.

**Comment by Fabricio20** [comment]
Ok, I'll see what I can do about it ;/
