### ISSUE TITLE
How can i change the "autorefresh" and the "refresh timer" messages?

### ISSUE THREAD

**Issue by ghost** [franga2000/BungeeStatus#18]
I've my webpage in spanish and i want to change the Auto Refresh and the Refresh Timer for Auto Refresco and Temporizador de Refresco respectively. How can i do this?

**Comment by franga2000** [comment]
The toolbar is generated on [line 7 of script.js](https://github.com/franga2000/BungeeStatus/blob/master/include/script.js#L7). You can change it there.

**Comment by ghost** [comment]
Thnx m8, ur job is awsome :)
If u want to see my page, see this itrios.org

2015-08-16 17:19 GMT+02:00 Miha Frangez notifications@github.com:
