### ISSUE TITLE
Plugins is an array that crashes iconv()

### ISSUE THREAD

**Issue by craftbyte** [franga2000/BungeeStatus#6]
As said, happens with Spigot servers. Also, remove the BEAUTIFY, since it breaks on some servers.

**Comment by franga2000** [comment]
This might be a problem with 1.8. I haven't tested it on 1.8 yet, but I assumed it works. I'll test it as soon as I get home.

**Comment by franga2000** [comment]
Fixed in version [1.6](https://github.com/franga2000/BungeeStatus/releases/tag/1.6)
Thanks for the feedback!
