### ISSUE TITLE
index.php issus

### ISSUE THREAD

**Issue by sch19970102** [franga2000/BungeeStatus#8]
I according to README.md the file, said to do, the results index.php prompt error. Error content is:
Parse error: syntax error, unexpected ':' in /www/web/bbs/public_html/server/mc/index.php on line 16
What should I do?

**Comment by franga2000** [comment]
1. I have no idea what you just said
2. I'll be releasing a new version this weekend so I suggest you wait for that. I fixed a lot of bugs

**Comment by sch19970102** [comment]
Thank you very much and I will wait for you release a new version.
